name: Test AWS Environment and Secrets

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Choose the environment to deploy to (staging or Development)"
        required: true
        default: "Development"

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    steps:
      - name: Check AWS Credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          if [ -z "$AWS_ACCESS_KEY_ID" ]; then
            echo "AWS_ACCESS_KEY_ID is not set"
          else
            echo "AWS_ACCESS_KEY_ID is set"
          fi
          if [ -z "$AWS_SECRET_ACCESS_KEY" ]; then
            echo "AWS_SECRET_ACCESS_KEY is not set"
          else
            echo "AWS_SECRET_ACCESS_KEY is set"
          fi
